# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-repositories-resource
resources:
  repositories:
    - repository: IOMDevopsRepo
      type: git
      name: order-iom-partner-devops
      ref: task/76533-ci-pipeline


trigger:
  branches:
    include:
      - '*'

jobs:

- job: CI
  pool: 'ubuntu-20.4-DS2_v2-adopt-adoptium-jdk'
  continueOnError: false
  timeoutInMinutes: 300
  workspace:
    clean: all

  steps:

  # see https://developercommunity.visualstudio.com/t/pipeline-template-from-other-repository/498657
  - template: steps.yml@IOMDevopsRepo

  - script: |
      echo "dummy script"
    timeoutInMinutes: 1
    displayName: "Dummy"
