# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-repositories-resource
resources:
  repositories:
    - repository: IOMDevopsRepo
      type: git
      name: order-iom-partner-devops
      ref: task/76533-ci-pipeline

trigger:
  branches:
    include:
      - '*'

# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#extend-from-a-template
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-other-repositories
extends:
  template: template.yml@IOMDevopsRepo
  parameters:
    ArtifactsFeed:                      order-iom-blueprint
    DockerRepoIOMServiceConnection:     order-iom-docker.intershop.de.dockerhub
    DockerRepoIOMName:                  docker.intershop.de/intershophub/
    DockerRepoProjectServiceConnection: order-iomci-ISH-ENG-IOM
    DockerRepoProjectNameCI:            iomci.azurecr.io/ci/
    DockerRepoProjectNameSnapshot:      iomci.azurecr.io/snapshot/
    DockerRepoProjectNameRelease:       iomci.azurecr.io/
